apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-upbound
spec:
  credentials:
    source: Secret
    secretRef:
      name: aws-creds
      namespace: crossplane-system
      key: creds