apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: dynamodb-table
  namespace: epinio
spec:
  publishConnectionDetailsTo:
    name: dynamodb-table-conn
    metadata:
      labels:
        app.kubernetes.io/instance: dynamodb-table
      annotations:
        kubed.appscode.com/sync: "kubernetes.io/metadata.name=epinio"
  providerConfigRef:
      name: aws-upbound
  forProvider:
    region: us-east-1
    attribute:
    - name: UserId
      type: S
    - name: GameTitle
      type: S
    - name: TopScore
      type: "N"
    billingMode: PROVISIONED
    globalSecondaryIndex:
    - hashKey: GameTitle
      name: GameTitleIndex
      nonKeyAttributes:
      - UserId
      projectionType: INCLUDE
      rangeKey: TopScore
      readCapacity: 10
      writeCapacity: 10
    hashKey: UserId
    rangeKey: GameTitle
    readCapacity: 20
    tags:
      Environment: production
      Name: dynamodb-table-1
    writeCapacity: 20
